//
//  ADNKeys.h
//  AppDotNet
//
//  Created by Me on 12/26/12.
//  Copyright (c) 2012 Matt Rubin. All rights reserved.
//

#ifndef AppDotNet_ADNKeys_h
#define AppDotNet_ADNKeys_h

#define KEY_ANNOTATIONS         @"annotations"
#define KEY_ANY_USER            @"any_user"
#define KEY_APP                 @"app"
#define KEY_AVATAR_IMAGE        @"avatar_image"
#define KEY_CANONICAL_URL       @"canonical_url"
#define KEY_CHANNEL_ID          @"channel_id"
#define KEY_CLIENT_ID           @"client_id"
#define KEY_CODE                @"code"
#define KEY_COUNTS              @"counts"
#define KEY_COVER_IMAGE         @"cover_image"
#define KEY_CREATED_AT          @"created_at"
#define KEY_DATA                @"data"
#define KEY_DESCRIPTION         @"description"
#define KEY_ENTITIES            @"entities"
#define KEY_FOLLOWERS           @"followers"
#define KEY_FOLLOWING           @"following"
#define KEY_FOLLOWS_YOU         @"follows_you"
#define KEY_HAS_UNREAD          @"has_unread"
#define KEY_HASHTAGS            @"hashtags"
#define KEY_HEIGHT              @"height"
#define KEY_HTML                @"html"
#define KEY_ID                  @"id"
#define KEY_IMMUTABLE           @"immutable"
#define KEY_IS_DELETED          @"is_deleted"
#define KEY_LEN                 @"len"
#define KEY_LINK                @"link"
#define KEY_LINKS               @"links"
#define KEY_LOCALE              @"locale"
#define KEY_MACHINE_ONLY        @"machine_only"
#define KEY_MENTIONS            @"mentions"
#define KEY_META                @"meta"
#define KEY_NAME                @"name"
#define KEY_NAME                @"name"
#define KEY_NUM_REPLIES         @"num_replies"
#define KEY_OWNER               @"owner"
#define KEY_POS                 @"pos"
#define KEY_POSTS               @"posts"
#define KEY_PUBLIC              @"public"
#define KEY_READERS             @"readers"
#define KEY_RECENT_MESSAGE_ID   @"recent_message_id"
#define KEY_REPLY_TO            @"reply_to"
#define KEY_SCOPES              @"scopes"
#define KEY_SOURCE              @"source"
#define KEY_STARS               @"stars"
#define KEY_TEXT                @"text"
#define KEY_THREAD_ID           @"thread_id"
#define KEY_TIMEZONE            @"timezone"
#define KEY_TYPE                @"type"
#define KEY_URL                 @"url"
#define KEY_USER                @"user"
#define KEY_USER_IDS            @"user_ids"
#define KEY_USERNAME            @"username"
#define KEY_VALUE               @"value"
#define KEY_WIDTH               @"width"
#define KEY_WRITERS             @"writers"
#define KEY_YOU                 @"you"
#define KEY_YOU_CAN_EDIT        @"you_can_edit"
#define KEY_YOU_FOLLOW          @"you_follow"
#define KEY_YOU_MUTED           @"you_muted"
#define KEY_YOU_SUBSCRIBED      @"you_subscribed"

#endif
